// Sample evaluation data for the Company Evaluation page.
// Replace with an API call when the backend is ready.

export const evaluationStats = {
  totalStudents: 18,
  evaluated: 12,
  pending: 6,
  avgRating: 4.28,
};

export const evaluationStudents = [
  {
    id: 1,
    name: "Rahul Sharma",
    role: "Web Development Intern",
    email: "rahul@gmail.com",
    phone: "+91 98765 43210",
    location: "Pune, Maharashtra",
    avatar: "https://i.pravatar.cc/80?img=12",
    opportunity: "Web Development Intern",
    department: "Computer Science",
    evaluatedOn: "15 Jul 2025",
    evaluatedBy: "Mentor - ABC Technologies",
    overallRating: 4.2,
    status: "Evaluated",
    criteria: [
      { label: "Technical Skills", value: 4.5 },
      { label: "Communication", value: 4.0 },
      { label: "Teamwork", value: 4.0 },
      { label: "Punctuality", value: 4.0 },
      { label: "Problem Solving", value: 4.5 },
    ],
    comments:
      "Rahul has shown great dedication and learning ability. He completes tasks on time and hits technical skills are improving consistently. Keep up the good work!",
  },
  {
    id: 2,
    name: "Priya Patel",
    role: "Data Science Intern",
    email: "priyap@gmail.com",
    phone: "+91 98123 45678",
    location: "Mumbai, Maharashtra",
    avatar: "https://i.pravatar.cc/80?img=32",
    opportunity: "Data Science Intern",
    department: "Data Science",
    evaluatedOn: "14 Jul 2025",
    evaluatedBy: "Mentor - ABC Technologies",
    overallRating: 4.9,
    status: "Evaluated",
    criteria: [
      { label: "Technical Skills", value: 5.0 },
      { label: "Communication", value: 4.8 },
      { label: "Teamwork", value: 4.9 },
      { label: "Punctuality", value: 5.0 },
      { label: "Problem Solving", value: 4.8 },
    ],
    comments:
      "Priya consistently delivers high-quality work and shows strong analytical thinking. An excellent addition to the team.",
  },
  {
    id: 3,
    name: "Ankeet Singh",
    role: "UI/UX Design Intern",
    email: "ankeet@gmail.com",
    phone: "+91 99887 66554",
    location: "Nagpur, Maharashtra",
    avatar: "https://i.pravatar.cc/80?img=14",
    opportunity: "UI/UX Design Intern",
    department: "IT / Design",
    evaluatedOn: "12 Jul 2025",
    evaluatedBy: "Mentor - ABC Technologies",
    overallRating: 4.0,
    status: "Evaluated",
    criteria: [
      { label: "Technical Skills", value: 4.0 },
      { label: "Communication", value: 4.0 },
      { label: "Teamwork", value: 4.0 },
      { label: "Punctuality", value: 3.8 },
      { label: "Problem Solving", value: 4.2 },
    ],
    comments:
      "Solid design fundamentals and a good eye for detail. Could improve on communicating design decisions to the team.",
  },
  {
    id: 4,
    name: "Sneha Verma",
    role: "Web Development Intern",
    email: "snehav@gmail.com",
    phone: "+91 91234 56789",
    location: "Pune, Maharashtra",
    avatar: "https://i.pravatar.cc/80?img=47",
    opportunity: "Web Development Intern",
    department: "Computer Science",
    evaluatedOn: "10 Jul 2025",
    evaluatedBy: "Mentor - ABC Technologies",
    overallRating: 3.8,
    status: "Evaluated",
    criteria: [
      { label: "Technical Skills", value: 3.8 },
      { label: "Communication", value: 3.6 },
      { label: "Teamwork", value: 4.0 },
      { label: "Punctuality", value: 3.5 },
      { label: "Problem Solving", value: 4.0 },
    ],
    comments:
      "Sneha is steadily improving. Needs to work on punctuality and proactive communication with the team.",
  },
  {
    id: 5,
    name: "Aman Gupta",
    role: "Data Analyst Intern",
    email: "amang@gmail.com",
    phone: "+91 90123 45678",
    location: "Nashik, Maharashtra",
    avatar: "https://i.pravatar.cc/80?img=51",
    opportunity: "Data Analyst Intern",
    department: "Data Science",
    evaluatedOn: "09 Jul 2025",
    evaluatedBy: "Mentor - ABC Technologies",
    overallRating: 4.4,
    status: "Evaluated",
    criteria: [
      { label: "Technical Skills", value: 4.5 },
      { label: "Communication", value: 4.2 },
      { label: "Teamwork", value: 4.3 },
      { label: "Punctuality", value: 4.5 },
      { label: "Problem Solving", value: 4.5 },
    ],
    comments:
      "Aman brings strong analytical rigor to every task and collaborates well with the rest of the team.",
  },
  {
    id: 6,
    name: "Neha Kulkarni",
    role: "Android Developer Intern",
    email: "nehak@gmail.com",
    phone: "+91 89012 34567",
    location: "Pune, Maharashtra",
    avatar: "https://i.pravatar.cc/80?img=25",
    opportunity: "Android Developer Intern",
    department: "Computer Science",
    evaluatedOn: null,
    evaluatedBy: null,
    overallRating: null,
    status: "Pending",
    criteria: [],
    comments: "Evaluation not yet submitted.",
  },
  {
    id: 7,
    name: "Vikram Purohit",
    role: "Cybersecurity Intern",
    email: "vikramp@gmail.com",
    phone: "+91 88901 23456",
    location: "Aurangabad, Maharashtra",
    avatar: "https://i.pravatar.cc/80?img=60",
    opportunity: "Cybersecurity Intern",
    department: "Information Tech",
    evaluatedOn: null,
    evaluatedBy: null,
    overallRating: null,
    status: "Pending",
    criteria: [],
    comments: "Evaluation not yet submitted.",
  },
  {
    id: 8,
    name: "Megha Desai",
    role: "Digital Marketing Intern",
    email: "meghad@gmail.com",
    phone: "+91 87890 12345",
    location: "Thane, Maharashtra",
    avatar: "https://i.pravatar.cc/80?img=45",
    opportunity: "Digital Marketing Intern",
    department: "Marketing",
    evaluatedOn: null,
    evaluatedBy: null,
    overallRating: null,
    status: "Pending",
    criteria: [],
    comments: "Evaluation not yet submitted.",
  },
];

export const opportunityOptions = [
  "Web Development Intern",
  "Data Science Intern",
  "UI/UX Design Intern",
  "Data Analyst Intern",
  "Android Developer Intern",
  "Cybersecurity Intern",
  "Digital Marketing Intern",
];

export const departmentOptions = [
  "Computer Science",
  "Data Science",
  "IT / Design",
  "Information Tech",
  "Marketing",
];

export const statusOptions = ["Evaluated", "Pending"];
